### ISSUE TITLE
Criando arquitetura basica do projeto

### ISSUE THREAD

**Issue by lucasres** [lucasres/adr-gen#1]
# Descrição 

* O projeto deve rodar de forma CLI
* Escolhe um lib para lidar com o CLI no Go lang
* Permitir a adição de puglins(envio para confluence, email, gerar arquivo, ...)

**Comment by RafaelYon** [comment]
Pensando que o projeto deve funcionar com diferentes casos, seja de linguagem (arquivos de input) quanto com de saídas (confluence, e-mail, arquivos .md)  acredito que o projeto pode se beneficiar bastante com o Pipe and Filters pattern

**Comment by RafaelYon** [comment]
Acredito que devemos usar a lib https://github.com/spf13/cobra para lidar com as necessidades comuns de um aplicação CLI pelos seguintes motivos:
- Grande quantidade de funcionalidades
- Cobertura de testes 
- Grande número de contribuidores (maior probabilidade de suporte)
- Maturidade, a mesma possui desenvolvimento ativo desde 2013

**Comment by RafaelYon** [comment]
Como nosso projeto é um ferramenta com o objetivo de auxiliar a documentação das decisões tomadas durante um determinado projeto deixando essa documentação no código, não consigo pensar na implementação de regras de negocio, assim não vejo a necessidade de um arquitetura focada no domínio de negócios.

Generalizando a funcionalidade principal do projeto, podemos explica-lo como:
> Uma ferramenta de encontrar padrões em arquivos, extrair e formatar informações

Com isso, a mesma poderia servir para outras necessidades além de "...facilitar a criação de [ADR](https://github.com/joelparkerhenderson/architecture-decision-record) para projetos."

Dessa forma acredito que a seguinte divisão de pastas permite uma evolução da ferramenta:
```
comando_que_incia_operacao.go
adr/
    input/
        php.go
        go.go
    ouput/
        confluence.go
        markdown.go
todos/
    input/
        ruby.go
        python.go
    output/
        todo_list.go
        github_issues.go
```

Portanto, acredito que o padrão https://github.com/golang-standards/project-layout/ atende essa estrutura, pelos seguintes motivos:
 - É simples, define apenas 3 diretórios para código GO
 - Os comandos CLI que iniciam os processos da aplicação devem existir no diretório `cmd`
 - Código útil que pode ser usados por outros projetos reside no diretório `pkg`. Em nosso caso, poderíamos deixar os clientes de APIs externas, como o Confluence, nessa camada.
 - Código exclusivo para funcionamento do aplicação fica abaixo de `internal`. O compilador Go impede que código nessa camada seja usado por projetos externos, o que nos permite focar em nosso aplicativo sem se preocupar com o mundo externo.

É importante ressaltar que a documentação desse padrão foi gentilmente traduzida para o Português BR: https://github.com/golang-standards/project-layout/blob/master/README_ptBR.md

**Comment by RafaelYon** [comment]
O ***golang-standards/project-layout*** define que o diretório `cmd` deve armazenar:
> Principais aplicações para este projeto.
> 
> O nome do diretório para cada aplicação deve corresponder ao nome do executável que você deseja ter (ex. /cmd/myapp).
> https://github.com/golang-standards/project-layout/blob/master/README_ptBR.md#cmd

Entretanto, acredito que esse projeto não possuirá mais de uma aplicação e sim que a customização poderá ser realizada por meio de configurações adicionais.

Como a lib https://github.com/spf13/cobra permite que uma aplicação possua diversos comandos, penso que poderíamos modificar um pouco a responsabilidade do diretório `cmd`, deixando o mesmo responsável por armazenar esses diversos comandos, por exemplo:
```
cmd/
	help.go
	version.go
	analyze.go
```
